# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        env_file:
            - ./.env
        networks:
            - sail
#        depends_on:
#            - mysql
#            - redis
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'sailredis:/data'
#        networks:
#            - sail
networks:
    sail:
        driver: bridge
#volumes:
#    sailmysql:
#        driver: local
#    sailredis:
#        driver: local
